//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_MAPBACKGROUND               157
#define IDB_SWORD1                      161
#define IDB_BITMAP4                     163
#define IDB_GREATSWORDLOGO              163
#define IDB_BITMAP5                     164
#define IDB_MAPGROUND                   164
#define IDB_BITMAP6                     165
#define IDB_LONGGROUND                  165
#define IDB_BITMAP7                     166
#define IDB_MAPGROUND1                  166
#define IDB_BITMAP8                     167
#define IDB_MAPSLIDE1                   167
#define IDB_BITMAP9                     168
#define IDB_MAPSLIDE2                   168
#define IDB_HeroNoMove_1                169
#define IDB_HeroNoMove_2                170
#define IDB_HeroNoMove_3                171
#define IDB_HeroNoMove_4                172
#define IDB_BITMAP14                    173
#define IDB_HeroNoMove_5                173
#define IDB_HEROMOVERIGHT_1             174
#define IDB_HEROMOVERIGHT_2             175
#define IDB_HEROMOVERIGHT_3             176
#define IDB_HEROMOVERIGHT_4             177
#define IDB_BITMAP15                    178
#define IDB_HEROMOVERIGHT_5             178
#define IDB_HEROMOVELEFT_1              179
#define IDB_HEROMOVELEFT_2              180
#define IDB_HEROMOVELEFT_3              181
#define IDB_HEROMOVELEFT_4              182
#define IDB_BITMAP16                    183
#define IDB_HEROMOVELEFT_5              183
#define IDB_HEROJUMP_1                  184
#define IDB_HEROJUMP_2                  185
#define IDB_HEROJUMP_3                  186
#define IDB_HEROJUMP_4                  187
#define IDB_HEROJUMP_5                  188
#define IDB_HEROJUMP_6                  189
#define IDB_HEROJUMP_7                  190
#define IDB_BITMAP20                    191
#define IDB_HEROJUMP_8                  191
#define IDB_HERONOMOVELEFT_1            192
#define IDB_HERONOMOVELEFT_2            193
#define IDB_HERONOMOVELEFT_3            194
#define IDB_HERONOMOVELEFT_4            195
#define IDB_BITMAP17                    196
#define IDB_HERONOMOVELEFT_5            196
#define IDB_BITMAP12                    199
#define IDB_SUNFLOWERRIGHTWALK_1        200
#define IDB_SUNFLOWERRIGHTWALK_2        201
#define IDB_SUNFLOWERRIGHTWALK_3        202
#define IDB_SUNFLOWERRIGHTWALK_4        203
#define IDB_SUNFLOWERRIGHTWALK_5        204
#define IDB_SUNFLOWERRIGHTWALK_6        205
#define IDB_SUNFLOWERRIGHTWALK_7        206
#define IDB_SUNFLOWERRIGHTWALK_8        207
#define IDB_BITMAP24                    208
#define IDB_SUNFLOWERRIGHTWALK_9        208
#define IDB_sword_1                     209
#define IDB_sword_2                     210
#define IDB_sword_3                     211
#define IDB_sword_4                     212
#define IDB_sword_5                     213
#define IDB_sword_6                     214
#define IDB_BITMAP22                    215
#define IDB_sword_7                     215
#define IDB_SWORD_1_1                   216
#define IDB_SWORD_2_1                   217
#define IDB_SWORD_3_1                   218
#define IDB_SWORD_4_1                   219
#define IDB_SWORD_5_1                   220
#define IDB_SWORD_6_1                   221
#define IDB_BITMAP23                    222
#define IDB_SWORD_7_1                   222
#define IDB_HEROATTACK_1                223
#define IDB_HEROATTACK_2                224
#define IDB_HEROATTACK_3                225
#define IDB_BITMAP18                    226
#define IDB_HEROATTACK_4                226
#define IDB_SWORDATTACK_1               227
#define IDB_SWORDATTACK_2               228
#define IDB_SWORDATTACK_3               229
#define IDB_SWORDATTACK_4               230
#define IDB_SWORDATTACK_5               231
#define IDB_SWORDATTACK_6               232
#define IDB_BITMAP26                    233
#define IDB_SWORDATTACK_7               233
#define IDB_HEROATTACK_1_1              234
#define IDB_HEROATTACK_2_1              235
#define IDB_HEROATTACK_3_1              236
#define IDB_BITMAP19                    237
#define IDB_HEROATTACK_4_1              237
#define IDB_SWORDATTACK_1_1             238
#define IDB_SWORDATTACK_2_1             239
#define IDB_SWORDATTACK_3_1             240
#define IDB_SWORDATTACK_4_1             241
#define IDB_SWORDATTACK_5_1             242
#define IDB_SWORDATTACK_6_1             243
#define IDB_BITMAP28                    244
#define IDB_SWORDATTACK_7_1             244
#define IDB_SUNFLOWER_DEAD_0            245
#define IDB_SUNFLOWER_DEAD_1            246
#define IDB_SUNFLOWER_DEAD_2            247
#define IDB_SUNFLOWER_DEAD_3            248
#define IDB_BITMAP25                    249
#define IDB_SUNFLOWER_DEAD_4            249
#define IDB_HEROJUMP_0_1                250
#define IDB_HEROJUMP_1_1                251
#define IDB_HEROJUMP_2_1                252
#define IDB_HEROJUMP_3_1                253
#define IDB_BITMAP27                    254
#define IDB_HEROJUMP_4_1                254
#define IDB_BITMAP10                    255
#define IDB_LIFEBAR                     255
#define IDB_BITMAP11                    256
#define IDB_LIFEBARHEAD                 256
#define IDB_DASH_LEFT_1                 257
#define IDB_DASH_LEFT_2                 258
#define IDB_DASH_LEFT_3                 259
#define IDB_BITMAP30                    260
#define IDB_DASH_LEFT_4                 260
#define IDB_DASH_RIGHT_1                261
#define IDB_DASH_RIGHT_2                262
#define IDB_DASH_RIGHT_3                263
#define IDB_BITMAP31                    264
#define IDB_DASH_RIGHT_4                264
#define IDB_ROLL_LEFT_1                 265
#define IDB_ROLL_LEFT_2                 266
#define IDB_ROLL_LEFT_3                 267
#define IDB_ROLL_LEFT_4                 268
#define IDB_ROLL_RIGHT_1                269
#define IDB_ROLL_RIGHT_2                270
#define IDB_ROLL_RIGHT_3                271
#define IDB_BITMAP33                    272
#define IDB_ROLL_RIGHT_4                272
#define IDB_ROLL_LEFT_5                 273
#define IDB_ROLL_LEFT_6                 274
#define IDB_ROLL_RIGHT_5                275
#define IDB_BITMAP29                    276
#define IDB_ROLL_RIGHT_6                276
#define IDB_RED_NUM_0                   277
#define IDB_RED_NUM_1                   278
#define IDB_RED_NUM_2                   279
#define IDB_RED_NUM_3                   280
#define IDB_RED_NUM_4                   281
#define IDB_RED_NUM_5                   282
#define IDB_RED_NUM_6                   283
#define IDB_RED_NUM_7                   284
#define IDB_RED_NUM_8                   285
#define IDB_BITMAP40                    286
#define IDB_RED_NUM_9                   286
#define IDB_OLD_MAN_1                   287
#define IDB_OLD_MAN_2                   288
#define IDB_BITMAP32                    289
#define IDB_OLD_MAN_3                   289
#define IDB_HIT_TOP_ARROW_1             290
#define IDB_BITMAP21                    291
#define IDB_HIT_TOP_ARROW_2             291
#define IDB_TALK_BAR_1                  292
#define IDB_TALK_BAR_2                  293
#define IDB_TALK_BAR_3                  294
#define IDB_BITMAP36                    295
#define IDB_TALK_BAR_4                  295
#define IDB_GIRAFFE_1                   296
#define IDB_GIRAFFE_2                   297
#define IDB_GIRAFFE_3                   298
#define IDB_GIRAFFE_4                   299
#define IDB_BITMAP38                    300
#define IDB_GIRAFFE_5                   300
#define IDB_UI_GAME_START               301
#define IDB_UI_LEVEL_UP_INTERFACE       302
#define IDB_UI_LEVEL_UP_BAR             303
#define IDB_UI_QUIT                     304
#define IDB_BITMAP39                    305
#define IDB_UI_PAUSE                    305
#define IDB_WORLDMAP_1                  306
#define IDB_BITMAP34                    307
#define IDB_WORLDMAP_UI                 307
#define IDB_STATUE                      308
#define IDB_BITMAP35                    309
#define IDB_STATUE_BROKEN               309
#define IDB_BITMAP13                    310
#define IDB_BLACKMASK                   310
#define IDB_SWORDDASHLEFT_0             311
#define IDB_SWORDDASHLEFT_1             312
#define IDB_SWORDDASHLEFT_2             313
#define IDB_BITMAP43                    314
#define IDB_SWORDDASHLEFT_3             314
#define IDB_SWORDDASHRIGHT_0            315
#define IDB_SWORDDASHRIGHT_1            316
#define IDB_SWORDDASHRIGHT_2            317
#define IDB_BITMAP44                    318
#define IDB_SWORDDASHRIGHT_3            318
#define IDB_SUNFLOWERLEFTWALK_0         319
#define IDB_SUNFLOWERLEFTWALK_1         320
#define IDB_SUNFLOWERLEFTWALK_2         321
#define IDB_SUNFLOWERLEFTWALK_3         322
#define IDB_SUNFLOWERLEFTWALK_4         323
#define IDB_SUNFLOWERLEFTWALK_5         324
#define IDB_SUNFLOWERLEFTWALK_6         325
#define IDB_SUNFLOWERLEFTWALK_7         326
#define IDB_BITMAP50                    327
#define IDB_SUNFLOWERLEFTWALK_8         327
#define IDB_SUNFLOWERATTACKRIGHT_0      328
#define IDB_SUNFLOWERATTACKRIGHT_1      329
#define IDB_SUNFLOWERATTACKRIGHT_2      330
#define IDB_SUNFLOWERATTACKRIGHT_3      331
#define IDB_SUNFLOWERATTACKRIGHT_4      332
#define IDB_SUNFLOWERATTACKRIGHT_5      333
#define IDB_SUNFLOWERATTACKRIGHT_6      334
#define IDB_SUNFLOWERATTACKLEFT_0       335
#define IDB_SUNFLOWERATTACKLEFT_1       336
#define IDB_SUNFLOWERATTACKLEFT_2       337
#define IDB_SUNFLOWERATTACKLEFT_3       338
#define IDB_SUNFLOWERATTACKLEFT_4       339
#define IDB_SUNFLOWERATTACKLEFT_5       340
#define IDB_BITMAP49                    341
#define IDB_SUNFLOWERATTACKLEFT_6       341
#define IDB_SUNFLOWERBULLET_0           342
#define IDB_SUNFLOWERBULLET_1           343
#define IDB_SUNFLOWERBULLET_2           344
#define IDB_SUNFLOWERBULLET_3           345
#define IDB_SUNFLOWERBULLET_4           346
#define IDB_SUNFLOWERBULLET_5           347
#define IDB_SUNFLOWERBULLET_6           348
#define IDB_SUNFLOWERBULLET_7           349
#define IDB_SUNFLOWERBULLET_BROKEN_0    350
#define IDB_SUNFLOWERBULLET_BROKEN_1    351
#define IDB_BITMAP54                    352
#define IDB_SUNFLOWERBULLET_BROKEN_2    352
#define IDB_CACTUSNOMOVE_0              353
#define IDB_CACTUSNOMOVE_1              354
#define IDB_CACTUSNOMOVE_2              355
#define IDB_CACTUSATTACK_0              356
#define IDB_CACTUSATTACK_1              357
#define IDB_CACTUSATTACK_2              358
#define IDB_CACTUSATTACK_3              359
#define IDB_CACTUSATTACK_4              360
#define IDB_CACTUSATTACK_5              361
#define IDB_CACTUSATTACK_6              362
#define IDB_CACTUSATTACK_7              363
#define IDB_CACTUSDEAD_0                364
#define IDB_CACTUSDEAD_1                365
#define IDB_CACTUSDEAD_2                366
#define IDB_CACTUSDEAD_3                367
#define IDB_CACTUSDEAD_4                368
#define IDB_CACTUSDEAD_5                369
#define IDB_CACTUSDEAD_6                370
#define IDB_BITMAP51                    371
#define IDB_CACTUSDEAD_7                371
#define IDB_NUM_BLK_0                   372
#define IDB_NUM_BLK_1                   373
#define IDB_NUM_BLK_2                   374
#define IDB_NUM_BLK_3                   375
#define IDB_NUM_BLK_4                   376
#define IDB_NUM_BLK_5                   377
#define IDB_NUM_BLK_6                   378
#define IDB_NUM_BLK_7                   379
#define IDB_NUM_BLK_8                   380
#define IDB_BITMAP55                    381
#define IDB_NUM_BLK_9                   381
#define IDB_BITMAP42                    384
#define IDB_SWORDROLLRIGHT_0            385
#define IDB_SWORDROLLRIGHT_1            386
#define IDB_SWORDROLLRIGHT_2            387
#define IDB_BITMAP46                    388
#define IDB_SWORDROLLRIGHT_3            388
#define IDB_SWORDROLLLEFT_0             389
#define IDB_SWORDROLLLEFT_1             390
#define IDB_SWORDROLLLEFT_2             391
#define IDB_BITMAP47                    392
#define IDB_SWORDROLLLEFT_3             392
#define IDB_BITMAP37                    393
#define IDB_WHITE                       393
#define IDB_BRONZECOIN_0                394
#define IDB_BRONZECOIN_1                395
#define IDB_BRONZECOIN_2                396
#define IDB_BITMAP52                    397
#define IDB_BRONZECOIN_3                397
#define IDB_SILVERCOIN_0                398
#define IDB_SILVERCOIN_1                399
#define IDB_SILVERCOIN_2                400
#define IDB_BITMAP53                    401
#define IDB_SILVERCOIN_3                401
#define IDB_GOLDCOIN_0                  402
#define IDB_GOLDCOIN_1                  403
#define IDB_GOLDCOIN_2                  404
#define IDB_BITMAP56                    405
#define IDB_GOLDCOIN_3                  405
#define IDB_NUM_GOLD_0                  406
#define IDB_NUM_GOLD_1                  407
#define IDB_NUM_GOLD_2                  408
#define IDB_NUM_GOLD_3                  409
#define IDB_NUM_GOLD_4                  410
#define IDB_NUM_GOLD_5                  411
#define IDB_NUM_GOLD_6                  412
#define IDB_NUM_GOLD_7                  413
#define IDB_NUM_GOLD_8                  414
#define IDB_BITMAP63                    415
#define IDB_NUM_GOLD_9                  415
#define IDB_BITMAP41                    416
#define IDB_WORD_G                      416
#define IDB_BITMAP45                    417
#define IDB_WORD_GOLD                   417
#define IDB_CACTUSGETHIT_0              418
#define IDB_CACTUSGETHIT_1              419
#define IDB_BITMAP58                    420
#define IDB_CACTUSGETHIT_2              420
#define IDB_SUNFLOWERGETHITRIGHT_0      421
#define IDB_SUNFLOWERGETHITRIGHT_1      422
#define IDB_BITMAP59                    423
#define IDB_SUNFLOWERGETHITRIGHT_2      423
#define IDB_ENEMY_NUM_0                 424
#define IDB_ENEMY_NUM_1                 425
#define IDB_ENEMY_NUM_2                 426
#define IDB_ENEMY_NUM_3                 427
#define IDB_ENEMY_NUM_4                 428
#define IDB_ENEMY_NUM_5                 429
#define IDB_ENEMY_NUM_6                 430
#define IDB_ENEMY_NUM_7                 431
#define IDB_ENEMY_NUM_8                 432
#define IDB_BITMAP68                    433
#define IDB_ENEMY_NUM_9                 433
#define IDB_BITMAP3                     435
#define IDB_SUNFLOWER_LEFT              436
#define IDB_BITMAP57                    437
#define IDB_SUNFLOWER_RIGHT             437
#define IDB_FIRESWORDRIGHT_0            438
#define IDB_FIRESWORDRIGHT_1            439
#define IDB_FIRESWORDRIGHT_2            440
#define IDB_FIRESWORDRIGHT_3            441
#define IDB_FIRESWORDRIGHT_4            442
#define IDB_FIRESWORDRIGHT_5            443
#define IDB_FIRESWORDRIGHT_6            444
#define IDB_BITMAP48                    445
#define IDB_FIRESTONE                   445
#define IDB_FIRESWORDLEFT_0             446
#define IDB_FIRESWORDLEFT_1             447
#define IDB_FIRESWORDLEFT_2             448
#define IDB_FIRESWORDLEFT_3             449
#define IDB_FIRESWORDLEFT_4             450
#define IDB_FIRESWORDLEFT_5             451
#define IDB_BITMAP67                    452
#define IDB_FIRESWORDLEFT_6             452
#define IDB_REDPOTSMALL                 453
#define IDB_REDPOTFULL                  454
#define IDB_BITMAP62                    455
#define IDB_REDPOTMEDIUM                455
#define IDB_FIRECIRCLE_0                456
#define IDB_FIRECIRCLE_1                457
#define IDB_FIRECIRCLE_2                458
#define IDB_FIRECIRCLE_3                459
#define IDB_FIRECIRCLE_4                460
#define IDB_BITMAP69                    461
#define IDB_FIRECIRCLE_5                461
#define IDB_FIRE_0                      462
#define IDB_FIRE_1                      463
#define IDB_FIRE_2                      464
#define IDB_FIRE_3                      465
#define IDB_FIRE_4                      466
#define IDB_BITMAP70                    467
#define IDB_FIRE_5                      467
#define IDB_BOX                         468
#define IDB_DOOR                        469
#define IDB_POPUPSPIKE_0                470
#define IDB_POPUPSPIKE_1                471
#define IDB_POPUPSPIKE_2                472
#define IDB_POPUPSPIKE_3                473
#define IDB_PUSHBUTTONDOWN              474
#define IDB_PUSHBUTTONUP                475
#define IDB_SWITCH_OFF                  476
#define IDB_BITMAP75                    477
#define IDB_SWITCH_ON                   477
#define IDB_BITMAP60                    478
#define IDB_SHIELD_0                    478
#define IDB_HIT_0                       479
#define IDB_HIT_1                       480
#define IDB_HIT_2                       481
#define IDB_HIT_3                       482
#define IDB_BITMAP71                    483
#define IDB_HIT_4                       483
#define IDB_GAINLIFE_0                  484
#define IDB_GAINLIFE_1                  485
#define IDB_GAINLIFE_2                  486
#define IDB_GAINLIFE_3                  487
#define IDB_BITMAP72                    488
#define IDB_GAINLIFE_4                  488
#define IDB_BITMAP61                    489
#define IDB_REDSTONE                    489
#define IDB_BITMAP64                    490
#define IDB_GAINLIFE_UI                 490
#define IDB_ENEMYLIFEBAR_LONG           491
#define IDB_BITMAP66                    492
#define IDB_ENEMYLIFEBAR_0              492
#define IDB_HEROBULLET_UI               493
#define IDB_SHURIKAN_0                  494
#define IDB_BITMAP73                    495
#define IDB_SHURIKAN_1                  495
#define IDB_BITMAP65                    496
#define IDB_ITEMSHURIKAN                496
#define IDB_HEROTHROWLEFT_0             497
#define IDB_HEROTHROWLEFT_1             498
#define IDB_HEROTHROWLEFT_2             499
#define IDB_HEROTHROWLEFT_3             500
#define IDB_HEROTHROWRIGHT_0            501
#define IDB_HEROTHROWRIGHT_1            502
#define IDB_HEROTHROWRIGHT_2            503
#define IDB_BITMAP79                    504
#define IDB_HEROTHROWRIGHT_3            504
#define IDB_LIGHTNING_0                 505
#define IDB_LIGHTNING_2                 506
#define IDB_LIGHTNING_3                 507
#define IDB_LIGHTNING_1                 508
#define IDB_LIGHTNING_4                 509
#define IDB_LIGHTNING_5                 510
#define IDB_LIGHTNING_6                 511
#define IDB_LIGHTNING_7                 512
#define IDB_LIGHTNING_8                 513
#define IDB_LIGHTNING_9                 514
#define IDB_LIGHTNING_10                515
#define IDB_LIGHTNING_11                516
#define IDB_LIGHTNING_12                517
#define IDB_LIGHTNING_13                518
#define IDB_CLOUDBOSS_0                 519
#define IDB_CLOUDBOSS_1                 520
#define IDB_CLOUDBOSS_2                 521
#define IDB_CLOUDBOSS_3                 522
#define IDB_CLOUDBOSS_4                 523
#define IDB_CLOUDBOSS_5                 524
#define IDB_CLOUDBOSS_6                 525
#define IDB_CLOUDBOSS_7                 526
#define IDB_CLOUDBOSS_LEFT_0            527
#define IDB_CLOUDBOSS_LEFT_1            528
#define IDB_CLOUDBOSS_LEFT_2            529
#define IDB_CLOUDBOSS_LEFT_3            530
#define IDB_CLOUDBOSS_LEFT_4            531
#define IDB_CLOUDBOSS_LEFT_5            532
#define IDB_CLOUDBOSS_LEFT_6            533
#define IDB_BITMAP84                    534
#define IDB_CLOUDBOSS_LEFT_7            534
#define IDB_CLOUDWALKRIGHT_0            535
#define IDB_CLOUDWALKRIGHT_1            536
#define IDB_CLOUDWALKRIGHT_2            537
#define IDB_CLOUDWALKRIGHT_3            538
#define IDB_CLOUDWALKRIGHT_4            539
#define IDB_CLOUDWALKRIGHT_5            540
#define IDB_CLOUDWALKRIGHT_6            541
#define IDB_CLOUDWALKLEFT_0             542
#define IDB_CLOUDWALKLEFT_1             543
#define IDB_CLOUDWALKLEFT_2             544
#define IDB_CLOUDWALKLEFT_3             545
#define IDB_CLOUDWALKLEFT_4             546
#define IDB_CLOUDWALKLEFT_5             547
#define IDB_BITMAP83                    548
#define IDB_CLOUDWALKLEFT_6             548
#define IDB_CLOUDYATTACKRIGHT_0         549
#define IDB_CLOUDYATTACKRIGHT_1         550
#define IDB_CLOUDYATTACKRIGHT_2         551
#define IDB_CLOUDYATTACKRIGHT_3         552
#define IDB_CLOUDYATTACKRIGHT_4         553
#define IDB_CLOUDYATTACKRIGHT_5         554
#define IDB_CLOUDYATTACKRIGHT_6         555
#define IDB_CLOUDYATTACKRIGHT_7         556
#define IDB_CLOUDYATTACKRIGHT_8         557
#define IDB_CLOUDYATTACKRIGHT_9         558
#define IDB_CLOUDYATTACKLEFT_0          559
#define IDB_CLOUDYATTACKLEFT_1          560
#define IDB_CLOUDYATTACKLEFT_2          561
#define IDB_CLOUDYATTACKLEFT_3          562
#define IDB_CLOUDYATTACKLEFT_4          563
#define IDB_CLOUDYATTACKLEFT_5          564
#define IDB_CLOUDYATTACKLEFT_6          565
#define IDB_CLOUDYATTACKLEFT_7          566
#define IDB_CLOUDYATTACKLEFT_8          567
#define IDB_BITMAP88                    568
#define IDB_CLOUDYATTACKLEFT_9          568
#define IDB_CLOUDYDEAD_0                569
#define IDB_CLOUDYDEAD_1                570
#define IDB_CLOUDYDEAD_2                571
#define IDB_CLOUDYDEAD_3                572
#define IDB_CLOUDYDEAD_4                573
#define IDB_BITMAP81                    574
#define IDB_CLOUDYDEAD_5                574
#define IDB_BITMAP74                    575
#define IDB_INFECTED_UI                 575
#define IDB_GASROBOTSTANDRIGHT_0        576
#define IDB_GASROBOTSTANDRIGHT_1        577
#define IDB_GASROBOTSTANDRIGHT_2        578
#define IDB_GASROBOTSTANDRIGHT_3        579
#define IDB_GASROBOTSTANDLEFT_0         580
#define IDB_GASROBOTSTANDLEFT_1         581
#define IDB_GASROBOTSTANDLEFT_2         582
#define IDB_GASROBOTSTANDLEFT_3         583
#define IDB_GASROBOTFIRERIGHT_0         584
#define IDB_GASROBOTFIRERIGHT_1         585
#define IDB_GASROBOTFIRELEFT_0          586
#define IDB_GASROBOTFIRELEFT_1          587
#define IDB_GASROBOTATTACKRIGHT_0       588
#define IDB_GASROBOTATTACKRIGHT_1       589
#define IDB_GASROBOTATTACKRIGHT_2       590
#define IDB_GASROBOTATTACKRIGHT_3       591
#define IDB_GASROBOTATTACKRIGHT_4       592
#define IDB_GASROBOTATTACKRIGHT_5       593
#define IDB_GASROBOTATTACKRIGHT_6       594
#define IDB_GASROBOTATTACKLEFT_0        595
#define IDB_GASROBOTATTACKLEFT_1        596
#define IDB_GASROBOTATTACKLEFT_2        597
#define IDB_GASROBOTATTACKLEFT_3        598
#define IDB_GASROBOTATTACKLEFT_4        599
#define IDB_GASROBOTATTACKLEFT_5        600
#define IDB_GASROBOTATTACKLEFT_6        601
#define IDB_GASROBOTDEAD_0              602
#define IDB_BITMAP77                    603
#define IDB_GASROBOTDEAD_1              603
#define IDB_GAS_0                       604
#define IDB_GAS_1                       605
#define IDB_GAS_2                       606
#define IDB_GAS_3                       607
#define IDB_BITMAP85                    608
#define IDB_GAS_4                       608
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        609
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
