//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 產生的 Include 檔案。
// 由 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_BALL                        130
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_1                           139
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_MINUS                       148
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_MAPBACKGROUND               157
#define IDB_SWORD1                      161
#define IDB_BITMAP3                     162
#define IDB_BITMAP4                     163
#define IDB_GREATSWORDLOGO              163
#define IDB_BITMAP5                     164
#define IDB_MAPGROUND                   164
#define IDB_BITMAP6                     165
#define IDB_LONGGROUND                  165
#define IDB_BITMAP7                     166
#define IDB_MAPGROUND1                  166
#define IDB_BITMAP8                     167
#define IDB_MAPSLIDE1                   167
#define IDB_BITMAP9                     168
#define IDB_MAPSLIDE2                   168
#define IDB_HeroNoMove_1                169
#define IDB_HeroNoMove_2                170
#define IDB_HeroNoMove_3                171
#define IDB_HeroNoMove_4                172
#define IDB_BITMAP14                    173
#define IDB_HeroNoMove_5                173
#define IDB_HEROMOVERIGHT_1             174
#define IDB_HEROMOVERIGHT_2             175
#define IDB_HEROMOVERIGHT_3             176
#define IDB_HEROMOVERIGHT_4             177
#define IDB_BITMAP15                    178
#define IDB_HEROMOVERIGHT_5             178
#define IDB_HEROMOVELEFT_1              179
#define IDB_HEROMOVELEFT_2              180
#define IDB_HEROMOVELEFT_3              181
#define IDB_HEROMOVELEFT_4              182
#define IDB_BITMAP16                    183
#define IDB_HEROMOVELEFT_5              183
#define IDB_HEROJUMP_1                  184
#define IDB_HEROJUMP_2                  185
#define IDB_HEROJUMP_3                  186
#define IDB_HEROJUMP_4                  187
#define IDB_HEROJUMP_5                  188
#define IDB_HEROJUMP_6                  189
#define IDB_HEROJUMP_7                  190
#define IDB_BITMAP20                    191
#define IDB_HEROJUMP_8                  191
#define IDB_HERONOMOVELEFT_1            192
#define IDB_HERONOMOVELEFT_2            193
#define IDB_HERONOMOVELEFT_3            194
#define IDB_HERONOMOVELEFT_4            195
#define IDB_BITMAP17                    196
#define IDB_HERONOMOVELEFT_5            196
#define IDB_SUNFLOWERNOMOVE_1           197
#define IDB_SUNFLOWERNOMOVE_2           198
#define IDB_BITMAP12                    199
#define IDB_SUNFLOWERNOMOVE_3           199
#define IDB_SUNFLOWERRIGHTWALK_1        200
#define IDB_SUNFLOWERRIGHTWALK_2        201
#define IDB_SUNFLOWERRIGHTWALK_3        202
#define IDB_SUNFLOWERRIGHTWALK_4        203
#define IDB_SUNFLOWERRIGHTWALK_5        204
#define IDB_SUNFLOWERRIGHTWALK_6        205
#define IDB_SUNFLOWERRIGHTWALK_7        206
#define IDB_SUNFLOWERRIGHTWALK_8        207
#define IDB_BITMAP24                    208
#define IDB_SUNFLOWERRIGHTWALK_9        208
#define IDB_sword_1                     209
#define IDB_sword_2                     210
#define IDB_sword_3                     211
#define IDB_sword_4                     212
#define IDB_sword_5                     213
#define IDB_sword_6                     214
#define IDB_BITMAP22                    215
#define IDB_sword_7                     215
#define IDB_SWORD_1_1                   216
#define IDB_SWORD_2_1                   217
#define IDB_SWORD_3_1                   218
#define IDB_SWORD_4_1                   219
#define IDB_SWORD_5_1                   220
#define IDB_SWORD_6_1                   221
#define IDB_BITMAP23                    222
#define IDB_SWORD_7_1                   222
#define IDB_HEROATTACK_1                223
#define IDB_HEROATTACK_2                224
#define IDB_HEROATTACK_3                225
#define IDB_BITMAP18                    226
#define IDB_HEROATTACK_4                226
#define IDB_SWORDATTACK_1               227
#define IDB_SWORDATTACK_2               228
#define IDB_SWORDATTACK_3               229
#define IDB_SWORDATTACK_4               230
#define IDB_SWORDATTACK_5               231
#define IDB_SWORDATTACK_6               232
#define IDB_BITMAP26                    233
#define IDB_SWORDATTACK_7               233
#define IDB_HEROATTACK_1_1              234
#define IDB_HEROATTACK_2_1              235
#define IDB_HEROATTACK_3_1              236
#define IDB_BITMAP19                    237
#define IDB_HEROATTACK_4_1              237
#define IDB_SWORDATTACK_1_1             238
#define IDB_SWORDATTACK_2_1             239
#define IDB_SWORDATTACK_3_1             240
#define IDB_SWORDATTACK_4_1             241
#define IDB_SWORDATTACK_5_1             242
#define IDB_SWORDATTACK_6_1             243
#define IDB_BITMAP28                    244
#define IDB_SWORDATTACK_7_1             244
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        245
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
